# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 289237cafc390819c60edaaff6fce37feb6fb693b52ed9e7109673d3190d2785300b58cb7982e7a0fb2e30bc7684a72614ed23660a0e5d4bdaf5af9391109bb1

test:
  secret_key_base: 8b61f97266d42ba9b33582c67b9e4853ace9754e4f0e9511c938e415ac04e0eb25480600a86a3b3f081af50d42828e2a6c941e257d928bd200c9683c16f4eeba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
